spring:
  application:
    name: GerenciadorEscolar
  datasource:
    url: jdbc:postgresql://localhost:5432/escola
    username: postgres
    password: luiluisa10
    driver-class-name: org.postgresql.Driver
